# -*- coding: utf-8 -*-
"""
Audio to Text.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MPz1QnaoRfBJA0y_zwVDDNNF1QdY_qgF
"""

"""Pemanggilan Model SVC"""

# Import Library
import os
import wave 
import struct
import joblib
import numpy as np
import soundfile as sf
import sounddevice as sd

# Load the model
current_dir = os.path.dirname(os.path.realpath(__file__))
model_dir = os.path.join(current_dir, 'models\svc\svc.pkl')
model = joblib.load(model_dir)

""" Implementasi dan Prediksi oleh Model """

# User Input
print("Enter Word you want to play and predict to text:")
filename= input()

# Call Audio
current_dir = os.path.dirname(os.path.realpath(__file__))
test_dir = os.path.join(current_dir, 'test_sound_mono')
fp = os.path.join(test_dir, filename + '_2.wav')

# Playing Audio
print("\nPlaying audio...\n")
data, fs = sf.read(fp, dtype='float32')  
sd.play(data, fs)
status = sd.wait()  # Wait until file is done playing

# Read Data
sound_read = wave.open(fp,'rb')
length = sound_read.getnframes()
for i in range (length):
    waveData = sound_read.readframes(1)
    data = struct.unpack("<1h", waveData)

# Prediksi Oleh Model
aud_to_text = model.predict(np.array(data).reshape(1, -1))
print("Predicted text from audio file:")
print(aud_to_text, aud_to_text.dtype)

""" Kesimpulan

Akurasi Set Data : 2.25% (9/400 kata ditebak benar)

List audio yang ditebak dengan benar
*   bulan_1
*   bulan_3
*   bulan_4
*   bulan_5
*   bulan_6
*   bulan_7
*   bulan_8
*   sakit_0
*   sakit_1

Akurasi Data Real : 2% (1/50 kata ditebak benar)

List kata yang ditebak dengan benar
*   Harus

Hasil validasi silang berkisar antara 2-2.5% yang merupakan nilai rata-rata dari 5 nilai *fold* (*cross validation* 5-*fold*).

Nilai setiap *fold*-nya berkisar antara 1.25; 2.5; atau 3.75

Set Data Latih: 400 audio, dilakukan validasi dan set data (latih:uji) dibagi secara acak menjadi 80:20 (5-fold) oleh fungsi.

Set Data Uji: 50 audio, 50 kata, 1 audio per kata.

Total: 450 file audio (50 kata * 9 audio/kata).
"""